set EJB3_LIB=G:\3rdparty\tools\jboss-EJB-3.0_Embeddable_ALPHA_3\lib
call mvn install:install-file -DgeneratePom=true -Dfile=%EJB3_LIB%\antlr-2.7.5H3.jar -DgroupId=jboss-ejb3-embeddable_alpha3 -DartifactId=antlr-2.7.5H3 -Dversion=1.0alpha3 -Dpackaging=jar
call mvn install:install-file -DgeneratePom=true -Dfile=%EJB3_LIB%\asm-attrs.jar -DgroupId=jboss-ejb3-embeddable_alpha3 -DartifactId=asm-attrs -Dversion=1.0alpha3 -Dpackaging=jar
call mvn install:install-file -DgeneratePom=true -Dfile=%EJB3_LIB%\asm.jar -DgroupId=jboss-ejb3-embeddable_alpha3 -DartifactId=asm -Dversion=1.0alpha3 -Dpackaging=jar
call mvn install:install-file -DgeneratePom=true -Dfile=%EJB3_LIB%\cglib-2.1.1.jar -DgroupId=jboss-ejb3-embeddable_alpha3 -DartifactId=cglib-2.1.1 -Dversion=1.0alpha3 -Dpackaging=jar
call mvn install:install-file -DgeneratePom=true -Dfile=%EJB3_LIB%\commons-collections.jar -DgroupId=jboss-ejb3-embeddable_alpha3 -DartifactId=commons-collections -Dversion=1.0alpha3 -Dpackaging=jar
call mvn install:install-file -DgeneratePom=true -Dfile=%EJB3_LIB%\commons-logging-api.jar -DgroupId=jboss-ejb3-embeddable_alpha3 -DartifactId=commons-logging-api -Dversion=1.0alpha3 -Dpackaging=jar
call mvn install:install-file -DgeneratePom=true -Dfile=%EJB3_LIB%\commons-logging.jar -DgroupId=jboss-ejb3-embeddable_alpha3 -DartifactId=commons-logging -Dversion=1.0alpha3 -Dpackaging=jar
call mvn install:install-file -DgeneratePom=true -Dfile=%EJB3_LIB%\concurrent.jar -DgroupId=jboss-ejb3-embeddable_alpha3 -DartifactId=concurrent -Dversion=1.0alpha3 -Dpackaging=jar
call mvn install:install-file -DgeneratePom=true -Dfile=%EJB3_LIB%\dom4j.jar -DgroupId=jboss-ejb3-embeddable_alpha3 -DartifactId=dom4j -Dversion=1.0alpha3 -Dpackaging=jar
call mvn install:install-file -DgeneratePom=true -Dfile=%EJB3_LIB%\ejb3-persistence.jar -DgroupId=jboss-ejb3-embeddable_alpha3 -DartifactId=ejb3-persistence -Dversion=1.0alpha3 -Dpackaging=jar
call mvn install:install-file -DgeneratePom=true -Dfile=%EJB3_LIB%\hibernate-annotations.jar -DgroupId=jboss-ejb3-embeddable_alpha3 -DartifactId=hibernate-annotations -Dversion=1.0alpha3 -Dpackaging=jar
call mvn install:install-file -DgeneratePom=true -Dfile=%EJB3_LIB%\hibernate-entitymanager.jar -DgroupId=jboss-ejb3-embeddable_alpha3 -DartifactId=hibernate-entitymanager -Dversion=1.0alpha3 -Dpackaging=jar
call mvn install:install-file -DgeneratePom=true -Dfile=%EJB3_LIB%\hibernate3.jar -DgroupId=jboss-ejb3-embeddable_alpha3 -DartifactId=hibernate3 -Dversion=1.0alpha3 -Dpackaging=jar
call mvn install:install-file -DgeneratePom=true -Dfile=%EJB3_LIB%\hsqldb.jar -DgroupId=jboss-ejb3-embeddable_alpha3 -DartifactId=hsqldb -Dversion=1.0alpha3 -Dpackaging=jar
call mvn install:install-file -DgeneratePom=true -Dfile=%EJB3_LIB%\javassist.jar -DgroupId=jboss-ejb3-embeddable_alpha3 -DartifactId=javassist -Dversion=1.0alpha3 -Dpackaging=jar
call mvn install:install-file -DgeneratePom=true -Dfile=%EJB3_LIB%\jboss-annotations-ejb3.jar -DgroupId=jboss-ejb3-embeddable_alpha3 -DartifactId=jboss-annotations-ejb3 -Dversion=1.0alpha3 -Dpackaging=jar
call mvn install:install-file -DgeneratePom=true -Dfile=%EJB3_LIB%\jboss-aop-jdk50.jar -DgroupId=jboss-ejb3-embeddable_alpha3 -DartifactId=jboss-aop-jdk50 -Dversion=1.0alpha3 -Dpackaging=jar
call mvn install:install-file -DgeneratePom=true -Dfile=%EJB3_LIB%\jboss-aspect-library-jdk50.jar -DgroupId=jboss-ejb3-embeddable_alpha3 -DartifactId=jboss-aspect-library-jdk50 -Dversion=1.0alpha3 -Dpackaging=jar
call mvn install:install-file -DgeneratePom=true -Dfile=%EJB3_LIB%\jboss-common-jdbc-wrapper.jar -DgroupId=jboss-ejb3-embeddable_alpha3 -DartifactId=jboss-common-jdbc-wrapper -Dversion=1.0alpha3 -Dpackaging=jar
call mvn install:install-file -DgeneratePom=true -Dfile=%EJB3_LIB%\jboss-common.jar -DgroupId=jboss-ejb3-embeddable_alpha3 -DartifactId=jboss-common -Dversion=1.0alpha3 -Dpackaging=jar
call mvn install:install-file -DgeneratePom=true -Dfile=%EJB3_LIB%\jboss-container.jar -DgroupId=jboss-ejb3-embeddable_alpha3 -DartifactId=jboss-container -Dversion=1.0alpha3 -Dpackaging=jar
call mvn install:install-file -DgeneratePom=true -Dfile=%EJB3_LIB%\jboss-dependency.jar -DgroupId=jboss-ejb3-embeddable_alpha3 -DartifactId=jboss-dependency -Dversion=1.0alpha3 -Dpackaging=jar
call mvn install:install-file -DgeneratePom=true -Dfile=%EJB3_LIB%\jboss-ejb3.jar -DgroupId=jboss-ejb3-embeddable_alpha3 -DartifactId=jboss-ejb3 -Dversion=1.0alpha3 -Dpackaging=jar
call mvn install:install-file -DgeneratePom=true -Dfile=%EJB3_LIB%\jboss-ejb3x.jar -DgroupId=jboss-ejb3-embeddable_alpha3 -DartifactId=jboss-ejb3x -Dversion=1.0alpha3 -Dpackaging=jar
call mvn install:install-file -DgeneratePom=true -Dfile=%EJB3_LIB%\jboss-j2ee.jar -DgroupId=jboss-ejb3-embeddable_alpha3 -DartifactId=jboss-j2ee -Dversion=1.0alpha3 -Dpackaging=jar
call mvn install:install-file -DgeneratePom=true -Dfile=%EJB3_LIB%\jboss-j2se.jar -DgroupId=jboss-ejb3-embeddable_alpha3 -DartifactId=jboss-j2se -Dversion=1.0alpha3 -Dpackaging=jar
call mvn install:install-file -DgeneratePom=true -Dfile=%EJB3_LIB%\jboss-jca.jar -DgroupId=jboss-ejb3-embeddable_alpha3 -DartifactId=jboss-jca -Dversion=1.0alpha3 -Dpackaging=jar
call mvn install:install-file -DgeneratePom=true -Dfile=%EJB3_LIB%\jboss-local-jdbc.jar -DgroupId=jboss-ejb3-embeddable_alpha3 -DartifactId=jboss-local-jdbc -Dversion=1.0alpha3 -Dpackaging=jar
call mvn install:install-file -DgeneratePom=true -Dfile=%EJB3_LIB%\jboss-microcontainer.jar -DgroupId=jboss-ejb3-embeddable_alpha3 -DartifactId=jboss-microcontainer -Dversion=1.0alpha3 -Dpackaging=jar
call mvn install:install-file -DgeneratePom=true -Dfile=%EJB3_LIB%\jboss-remoting.jar -DgroupId=jboss-ejb3-embeddable_alpha3 -DartifactId=jboss-remoting -Dversion=1.0alpha3 -Dpackaging=jar
call mvn install:install-file -DgeneratePom=true -Dfile=%EJB3_LIB%\jboss-system.jar -DgroupId=jboss-ejb3-embeddable_alpha3 -DartifactId=jboss-system -Dversion=1.0alpha3 -Dpackaging=jar
call mvn install:install-file -DgeneratePom=true -Dfile=%EJB3_LIB%\jboss-transaction.jar -DgroupId=jboss-ejb3-embeddable_alpha3 -DartifactId=jboss-transaction -Dversion=1.0alpha3 -Dpackaging=jar
call mvn install:install-file -DgeneratePom=true -Dfile=%EJB3_LIB%\jboss-xa-jdbc.jar -DgroupId=jboss-ejb3-embeddable_alpha3 -DartifactId=jboss-xa-jdbc -Dversion=1.0alpha3 -Dpackaging=jar
call mvn install:install-file -DgeneratePom=true -Dfile=%EJB3_LIB%\jboss.jar -DgroupId=jboss-ejb3-embeddable_alpha3 -DartifactId=jboss -Dversion=1.0alpha3 -Dpackaging=jar
call mvn install:install-file -DgeneratePom=true -Dfile=%EJB3_LIB%\jbossmq.jar -DgroupId=jboss-ejb3-embeddable_alpha3 -DartifactId=jbossmq -Dversion=1.0alpha3 -Dpackaging=jar
call mvn install:install-file -DgeneratePom=true -Dfile=%EJB3_LIB%\jbosssx.jar -DgroupId=jboss-ejb3-embeddable_alpha3 -DartifactId=jbosssx -Dversion=1.0alpha3 -Dpackaging=jar
call mvn install:install-file -DgeneratePom=true -Dfile=%EJB3_LIB%\jnpserver.jar -DgroupId=jboss-ejb3-embeddable_alpha3 -DartifactId=jnpserver -Dversion=1.0alpha3 -Dpackaging=jar
call mvn install:install-file -DgeneratePom=true -Dfile=%EJB3_LIB%\log4j.jar -DgroupId=jboss-ejb3-embeddable_alpha3 -DartifactId=log4j -Dversion=1.0alpha3 -Dpackaging=jar
call mvn install:install-file -DgeneratePom=true -Dfile=%EJB3_LIB%\resolver.jar -DgroupId=jboss-ejb3-embeddable_alpha3 -DartifactId=resolver -Dversion=1.0alpha3 -Dpackaging=jar
call mvn install:install-file -DgeneratePom=true -Dfile=%EJB3_LIB%\trove.jar -DgroupId=jboss-ejb3-embeddable_alpha3 -DartifactId=trove -Dversion=1.0alpha3 -Dpackaging=jar
call mvn install:install-file -DgeneratePom=true -Dfile=%EJB3_LIB%\xercesImpl.jar -DgroupId=jboss-ejb3-embeddable_alpha3 -DartifactId=xercesImpl -Dversion=1.0alpha3 -Dpackaging=jar
call mvn install:install-file -DgeneratePom=true -Dfile=%EJB3_LIB%\xml-apis.jar -DgroupId=jboss-ejb3-embeddable_alpha3 -DartifactId=xml-apis -Dversion=1.0alpha3 -Dpackaging=jar
